import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Starter from "./home";
import Link from "next/link";


export default function Home() {
  return (
    <>
      {/* HELLO DARABIE */}
      <Head>
        <title>ITEC-SA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./img/Logos/Itec-logo.png" />
      </Head>
      <Starter></Starter>
    </>
  );
}
